# Generated by Django 4.2.1 on 2023-08-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_expired',
            field=models.DateTimeField(blank=True, null=True, verbose_name='token expired'),
        ),
    ]
