# Generated by Django 4.2.1 on 2023-08-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_token_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_expired',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
    ]
