# Generated by Django 4.2.1 on 2023-07-17 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(max_length=30, verbose_name='created at')),
                ('updated_at', models.CharField(blank=True, max_length=30, null=True, verbose_name='updated at')),
                ('product_name', models.CharField(max_length=255, verbose_name='product_name')),
                ('ec_site', models.CharField(max_length=50, verbose_name='ec_site')),
                ('purchase_url', models.CharField(max_length=500, verbose_name='purchase_url')),
                ('ebay_url', models.CharField(max_length=500, verbose_name='ebay_url')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='purchase_price')),
                ('sell_price_en', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='sell_price_en')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='profit')),
                ('prima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='prima')),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='export shipping fee')),
                ('quantity', models.IntegerField(null=True, verbose_name='quantity')),
                ('order_num', models.CharField(max_length=50, verbose_name='order_num')),
                ('ordered_at', models.CharField(max_length=30, verbose_name='ordered_at')),
                ('notes', models.CharField(blank=True, max_length=3000, null=True, verbose_name='notes')),
                ('created_by', models.CharField(max_length=64, verbose_name='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.ImageField(upload_to='productphoto', verbose_name='image file')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='width')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='height')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_jp', models.CharField(blank=True, max_length=250, null=True, verbose_name='title JP')),
                ('title_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='title EN')),
                ('description_jp', models.TextField(blank=True, null=True, verbose_name='description JP')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description EN')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeletedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(max_length=30, verbose_name='created at')),
                ('updated_at', models.CharField(max_length=30, verbose_name='updated at')),
                ('product_name', models.CharField(max_length=255, verbose_name='product_name')),
                ('ec_site', models.CharField(max_length=50, verbose_name='ec_site')),
                ('purchase_url', models.CharField(max_length=500, verbose_name='purchase_url')),
                ('ebay_url', models.CharField(max_length=500, verbose_name='ebay_url')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='purchase_price')),
                ('sell_price_en', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='sell_price_en')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='profit')),
                ('prima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='prima')),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='export shipping fee')),
                ('quantity', models.IntegerField(null=True, verbose_name='quantity')),
                ('order_num', models.CharField(max_length=50, verbose_name='order_num')),
                ('ordered_at', models.CharField(max_length=30, verbose_name='ordered_at')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('deleted_at', models.CharField(max_length=30, verbose_name='ordered_at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
