# Generated by Django 4.2.1 on 2023-05-16 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('title_jp', models.CharField(blank=True, max_length=255, null=True, verbose_name='title JP')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='title EN')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='brand')),
                ('condition', models.CharField(blank=True, choices=[('NEW', 'New'), ('USED', 'Used')], max_length=20, verbose_name='condition')),
                ('condition_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='condition Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='quantity')),
                ('location_country', models.CharField(choices=[('JAPAN', 'Japan')], default='JAPAN', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.ImageField(upload_to='productphoto', verbose_name='image file')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='width')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='height')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_jp', models.CharField(blank=True, max_length=250, null=True, verbose_name='title JP')),
                ('title_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='title EN')),
                ('description_jp', models.CharField(blank=True, max_length=250, null=True, verbose_name='description JP')),
                ('description_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='description EN')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
