# Generated by Django 4.2.1 on 2023-06-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_condition_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('1000', 'New'), ('3000', 'Used')], max_length=20, verbose_name='condition'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location_country',
            field=models.CharField(choices=[('JP', 'Japan')], default='JP', max_length=100),
        ),
    ]
