# Generated by Django 4.2.1 on 2023-06-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='point',
            field=models.IntegerField(null=True, verbose_name='point'),
        ),
    ]
