# Generated by Django 4.2.1 on 2023-06-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='quantity'),
        ),
    ]
