# Generated by Django 4.2.1 on 2023-06-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_category',
            field=models.IntegerField(null=True, verbose_name='item Category'),
        ),
    ]
