# Generated by Django 4.2.1 on 2023-06-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_number',
            field=models.IntegerField(null=True, verbose_name='item Number'),
        ),
    ]
