# Generated by Django 4.2.1 on 2023-06-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_item_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_en',
        ),
    ]
