# Generated by Django 4.2.1 on 2023-06-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_rename_price_product_price_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_jp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
    ]
