# Generated by Django 4.2.1 on 2023-06-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_price_jp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.TextField(null=True, verbose_name='comment'),
        ),
    ]
