# Generated by Django 4.2.1 on 2023-06-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='site'),
        ),
    ]
