# Generated by Django 4.2.1 on 2023-06-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_policy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='shipping Policy'),
        ),
    ]
