# Generated by Django 4.2.1 on 2023-06-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_shipping_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='item Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Publish', 'Publish'), ('End', 'End')], default='Draft', max_length=20, verbose_name='status'),
        ),
    ]
