# Generated by Django 4.2.1 on 2023-06-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_jp',
            field=models.IntegerField(blank=True, null=True, verbose_name='price'),
        ),
    ]
